# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-27 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.CharField(max_length=15, unique=True, verbose_name='手机号')),
                ('nickname', models.CharField(default='匿名用户', max_length=20, verbose_name='昵称')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性')], default='male', max_length=6, verbose_name='性别')),
                ('birthday', models.DateField(default='1990-01-01', verbose_name='生日')),
                ('location', models.CharField(choices=[('上海', '上海'), ('北京', '北京'), ('福州', '福州'), ('广州', '广州'), ('宁德', '宁德'), ('深圳', '深圳'), ('厦门', '厦门'), ('武汉', '武汉')], default='上海', max_length=15, verbose_name='现处城市')),
                ('avatar', models.CharField(max_length=256, verbose_name='头像')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
